spring.application.name=api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT}

payment.api.key=${PAY_SECRET_KEY}
payment.gateway.secret=${GATEWAY_SECRET_KEY}
payment.gateway.name=${GATEWAY_NAME}

# ==========================================
# POSTGRES CONFIG
# ==========================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# ==========================================
# KAFKA CONFIG
# ==========================================

spring.kafka.bootstrap-servers=${KAFKA_URL}
spring.kafka.admin.auto-create=true
spring.kafka.topic=${KAFKA_TOPIC}

# ==========================================
# PRODUCER CONFIG
# ==========================================

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ==========================================
# CONSUMER CONFIG
# ==========================================

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# ==========================================
# TRUSTED PACKAGE
# ==========================================

spring.kafka.consumer.properties.spring.json.trusted.packages=*